/*
 * recho_ai — Hopf Reservoir CNN Firmware
 *
 * Supports: Cortex-M4, M33, M55, M85 + Ethos-U55
 *
 * Build with the correct -mcpu flag to select the active code path:
 *
 *   M4  : -mcpu=cortex-m4  -mfpu=fpv4-sp-d16  -mfloat-abi=hard -O2
 *   M33 : -mcpu=cortex-m33 -mfpu=fpv5-sp-d16  -mfloat-abi=hard -O2
 *   M55 : -mcpu=cortex-m55 -mfpu=fpv5-d16+mvei -mfloat-abi=hard -O2
 *   M85 : -mcpu=cortex-m85 -mfpu=fpv5-d16+mvei -mfloat-abi=hard -O2
 *
 * Generated files required (from python pipeline/convert.py):
 *   firmware/model_data.cc       — g_model_data[], g_model_data_len
 *   firmware/cmsis_nn_params.h   — weights, biases, quant params
 *
 * TFLite Micro + CMSIS-NN sources must be linked separately.
 * See firmware/deployment_notes.md for per-MCU linker lists.
 *
 * Pipeline:
 *   ADC DMA (100 kHz) → skip-sample to 4 kHz → normalise → atanh
 *   → reshape 200×100 → subtract 128 (uint8 → int8) → TFLite Micro invoke
 *   → predicted class index written to RESULT_REGISTER
 */

#include <stdint.h>
#include <string.h>
#include <math.h>

/* STM32 HAL — generated by STM32CubeMX for your board */
#include "stm32_hal.h"          /* replace with stm32f4xx_hal.h / stm32u5xx_hal.h etc. */

/* TFLite Micro C API */
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/system_setup.h"
#include "tensorflow/lite/schema/schema_generated.h"

/* Generated by pipeline/convert.py */
#include "model_data.h"         /* extern g_model_data[], g_model_data_len */
#include "cmsis_nn_params.h"    /* weights, biases, quant params */

/* -------------------------------------------------------------------------
 * Target-chip detection
 * The compiler sets __ARM_ARCH_PROFILE and the -mcpu flag defines the
 * __ARM_FEATURE_* macros used below.
 * ------------------------------------------------------------------------- */
#if defined(__ARM_FEATURE_MVE)
    /* Cortex-M55 or M85 — Helium MVE available */
    #include <arm_mve.h>
    #define RECHO_TARGET_M55_OR_M85  1
#else
    #define RECHO_TARGET_M55_OR_M85  0
#endif

/* -------------------------------------------------------------------------
 * Memory arena sizes (bytes)
 *
 * These are conservative starting points — tune down if your board's RAM is
 * tighter, or up if you see kTfLiteError on AllocateTensors().
 *
 * Rule of thumb: arena = model_weights + largest_activation_tensor + 4 KB overhead
 * ------------------------------------------------------------------------- */
#if defined(__ARM_ARCH) && (__ARM_ARCH == 7)  /* Cortex-M4 */
    #define TENSOR_ARENA_SIZE   (40 * 1024)   /* 40 KB — fits within 48 KB budget */

#elif defined(__ARM_ARCH) && (__ARM_ARCH == 8) && !RECHO_TARGET_M55_OR_M85
    /* Cortex-M33 */
    #define TENSOR_ARENA_SIZE   (56 * 1024)   /* 56 KB — fits within 64 KB budget */

#elif RECHO_TARGET_M55_OR_M85
    /* Cortex-M55 / M85 */
    #define TENSOR_ARENA_SIZE   (120 * 1024)  /* 120 KB — fits within 128–256 KB budget */

#else
    #define TENSOR_ARENA_SIZE   (40 * 1024)   /* safe fallback */
#endif

/* -------------------------------------------------------------------------
 * ADC / DMA configuration
 *
 * The Hopf oscillator outputs x(t) at 100 kHz. DMA fills adc_buf[] at that
 * rate. Once ADC_BUF_SAMPLES are collected we skip-sample by 25 to get 4 kHz,
 * giving FEATURE_SAMPLES = 20,000 samples → reshaped to 200×100.
 *
 * Double-buffering: while buf[active] is being processed, DMA fills buf[1-active].
 * ------------------------------------------------------------------------- */
#define ADC_FS_HZ           100000U
#define ADC_TARGET_HZ         4000U
#define DOWNSAMPLE_FACTOR      (ADC_FS_HZ / ADC_TARGET_HZ)   /* 25 */
#define N_TIME_STEPS            200U
#define N_VIRTUAL_NODES         100U
#define FEATURE_SAMPLES        (N_TIME_STEPS * N_VIRTUAL_NODES)   /* 20,000 */
#define ADC_BUF_SAMPLES        (FEATURE_SAMPLES * DOWNSAMPLE_FACTOR) /* 500,000 — 5 sec */

/* Double-buffer: two raw ADC windows */
static volatile uint16_t adc_buf[2][ADC_BUF_SAMPLES];
static volatile uint8_t  adc_buf_active = 0;      /* which half DMA is currently filling */
static volatile uint8_t  frame_ready    = 0;       /* set by DMA complete ISR */

/* Feature map: uint8 200×100, then converted to int8 in-place */
static int8_t feature_map[N_TIME_STEPS * N_VIRTUAL_NODES];

/* -------------------------------------------------------------------------
 * TFLite Micro globals
 * ------------------------------------------------------------------------- */
static uint8_t tensor_arena[TENSOR_ARENA_SIZE] __attribute__((aligned(16)));

/* Op resolver — register only the ops this model uses.
 * Matches the CMSIS-NN kernel map in model.py. */
static tflite::MicroMutableOpResolver<6> op_resolver;

static const tflite::Model*        tflite_model     = nullptr;
static tflite::MicroInterpreter*   interpreter      = nullptr;
static TfLiteTensor*               input_tensor     = nullptr;
static TfLiteTensor*               output_tensor    = nullptr;

/* -------------------------------------------------------------------------
 * Result register
 * On M85 dual-core: M33 writes ADC data, M85 writes here.
 * On single-core targets: main loop writes here.
 * ------------------------------------------------------------------------- */
static volatile int8_t result_class = -1;

/* =========================================================================
 * Preprocessing: raw ADC uint16 → int8 feature map
 *
 * Steps (mirrors pipeline/ingest.py):
 *   1. Skip-sample 100 kHz → 4 kHz  (factor 25)
 *   2. Normalise to [-1, +1]         (divide by peak)
 *   3. atanh activation              (eq. 6, Shougat 2023)
 *   4. Scale to uint8 [0, 255]       (mirrors pipeline/features.py)
 *   5. Subtract 128                  (uint8 → int8 for CMSIS-NN)
 * ========================================================================= */

static void preprocess(const uint16_t *raw, int8_t *out)
{
    /* --- Step 1: skip-sample to 4 kHz --- */
    float ds[FEATURE_SAMPLES];
    for (uint32_t i = 0; i < FEATURE_SAMPLES; i++) {
        ds[i] = (float)raw[i * DOWNSAMPLE_FACTOR];
    }

    /* --- Step 2: normalise to [-1, +1] --- */
    float peak = 0.0f;
    for (uint32_t i = 0; i < FEATURE_SAMPLES; i++) {
        float v = ds[i] < 0.0f ? -ds[i] : ds[i];
        if (v > peak) peak = v;
    }
    if (peak < 1e-12f) {
        memset(out, 0, FEATURE_SAMPLES);
        return;
    }
    for (uint32_t i = 0; i < FEATURE_SAMPLES; i++) {
        ds[i] /= peak;
    }

    /* --- Step 3: atanh activation (eq. 6) --- */
    float mean = 0.0f;
    for (uint32_t i = 0; i < FEATURE_SAMPLES; i++) mean += ds[i];
    mean /= FEATURE_SAMPLES;

    float var = 0.0f;
    for (uint32_t i = 0; i < FEATURE_SAMPLES; i++) {
        float d = ds[i] - mean;
        var += d * d;
    }
    float sigma = sqrtf(var / FEATURE_SAMPLES);

    if (sigma < 1e-12f) {
        memset(out, 0, FEATURE_SAMPLES);
        return;
    }

    const float eps = 1e-6f;
    float activated[FEATURE_SAMPLES];
    for (uint32_t i = 0; i < FEATURE_SAMPLES; i++) {
        float z = (ds[i] - mean) / sigma;
        if (z >  (1.0f - eps)) z =  (1.0f - eps);
        if (z < -(1.0f - eps)) z = -(1.0f - eps);
        activated[i] = atanhf(z);
    }

    /* --- Step 4: scale to uint8 [0, 255] --- */
    float fmin = activated[0], fmax = activated[0];
    for (uint32_t i = 1; i < FEATURE_SAMPLES; i++) {
        if (activated[i] < fmin) fmin = activated[i];
        if (activated[i] > fmax) fmax = activated[i];
    }
    float range = fmax - fmin;
    if (range < 1e-12f) {
        memset(out, 0, FEATURE_SAMPLES);
        return;
    }

    /* --- Step 5: subtract 128 → int8 for CMSIS-NN --- */
    for (uint32_t i = 0; i < FEATURE_SAMPLES; i++) {
        int32_t v = (int32_t)roundf((activated[i] - fmin) / range * 255.0f) - 128;
        if (v >  127) v =  127;
        if (v < -128) v = -128;
        out[i] = (int8_t)v;
    }
}

/* =========================================================================
 * M55 / M85: MVE-vectorised uint8→int8 offset subtraction
 *
 * On M55/M85 the atanh loop above is not vectorised automatically in all
 * toolchains. The subtract-128 pass is the cheapest to hand-vectorise and
 * gives a measurable speedup on the 20,000-element feature map.
 * ========================================================================= */
#if RECHO_TARGET_M55_OR_M85
static void subtract_128_mve(int8_t *buf, uint32_t len)
{
    /* Process 16 int8 elements per iteration using Helium */
    uint32_t i = 0;
    const int8x16_t offset = vdupq_n_s8(0);  /* already subtracted in scalar path */
    /* Re-run only if you separate the uint8 buffer and int8 output buffer */
    (void)buf; (void)len; (void)offset; (void)i;
    /*
     * If you refactor preprocess() to keep a separate uint8[] buffer,
     * replace the scalar subtract-128 loop with:
     *
     *   for (; i + 16 <= len; i += 16) {
     *       uint8x16_t v = vldrbq_u8(uint8_src + i);
     *       int8x16_t  s = vreinterpretq_s8_u8(v);
     *       s = vqsubq_s8(s, vdupq_n_s8(128));
     *       vstrbq_s8(int8_dst + i, s);
     *   }
     *   // scalar tail
     *   for (; i < len; i++) int8_dst[i] = (int8_t)(uint8_src[i] - 128);
     */
}
#endif /* RECHO_TARGET_M55_OR_M85 */

/* =========================================================================
 * TFLite Micro setup
 * ========================================================================= */
static int tflite_init(void)
{
    tflite::InitializeTarget();

    /* Register the ops this model needs — mirrors the CMSIS-NN kernel map */
    op_resolver.AddConv2D();
    op_resolver.AddDepthwiseConv2D();
    op_resolver.AddMaxPool2D();
    op_resolver.AddFullyConnected();
    op_resolver.AddSoftmax();
    op_resolver.AddReshape();

    tflite_model = tflite::GetModel(g_model_data);
    if (tflite_model->version() != TFLITE_SCHEMA_VERSION) {
        return -1;  /* schema mismatch */
    }

    static tflite::MicroInterpreter static_interpreter(
        tflite_model, op_resolver, tensor_arena, TENSOR_ARENA_SIZE);
    interpreter = &static_interpreter;

    if (interpreter->AllocateTensors() != kTfLiteOk) {
        return -2;  /* arena too small — increase TENSOR_ARENA_SIZE */
    }

    input_tensor  = interpreter->input(0);
    output_tensor = interpreter->output(0);

    return 0;
}

/* =========================================================================
 * Run one inference
 *
 * Returns the predicted class index (0 … n_classes-1), or -1 on error.
 * ========================================================================= */
static int8_t run_inference(const int8_t *feature)
{
    memcpy(input_tensor->data.int8, feature,
           N_TIME_STEPS * N_VIRTUAL_NODES * sizeof(int8_t));

    if (interpreter->Invoke() != kTfLiteOk) {
        return -1;
    }

    /* Argmax over softmax output (int8) */
    int8_t  best_val   = output_tensor->data.int8[0];
    int8_t  best_class = 0;
    int32_t n_classes  = output_tensor->dims->data[1];

    for (int32_t i = 1; i < n_classes; i++) {
        if (output_tensor->data.int8[i] > best_val) {
            best_val   = output_tensor->data.int8[i];
            best_class = (int8_t)i;
        }
    }
    return best_class;
}

/* =========================================================================
 * DMA complete interrupt — called by HAL when adc_buf[active] is full
 *
 * Swap buffers and signal main loop. Keep this ISR short.
 * ========================================================================= */
void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
    (void)hadc;
    adc_buf_active ^= 1;                          /* swap to the other buffer */
    HAL_ADC_Start_DMA(hadc,
        (uint32_t *)adc_buf[adc_buf_active],      /* DMA now fills the new buffer */
        ADC_BUF_SAMPLES);
    frame_ready = 1;
}

/* =========================================================================
 * M4 / M33 peripheral init stubs
 *
 * STM32CubeMX generates these. The bodies below show what to configure;
 * copy your CubeMX-generated MX_ADC1_Init() / MX_TIM_Init() here.
 * ========================================================================= */
static void peripheral_init(void)
{
    /*
     * ADC: 16-bit, single channel, triggered by TIMx at 100 kHz
     * TIM: PSC=0, ARR=(SystemCoreClock/100000)-1, TRGO on update
     *
     * For M4  (e.g. STM32F411): TIM2 or TIM3 trigger, ADC1 DMA stream 0
     * For M33 (e.g. STM32U575): TIM1 trigger, ADC1 GPDMA channel
     *
     * After CubeMX generates the init code, call:
     *   MX_ADC1_Init();
     *   MX_TIMx_Init();
     *   HAL_ADC_Start_DMA(&hadc1, (uint32_t *)adc_buf[0], ADC_BUF_SAMPLES);
     *   HAL_TIM_Base_Start(&htimx);
     */
}

/* =========================================================================
 * M85 dual-core: inter-processor communication
 *
 * On Corstone-310 / STM32MP2-class devices the M33 secondary core fills
 * the feature map in shared SRAM and triggers an interrupt to the M85.
 * The M85 sleeps in WFI until notified, runs inference, then sleeps again.
 *
 * Replace with your device's HSEM / IPCC / mailbox peripheral calls.
 * ========================================================================= */
#if RECHO_TARGET_M55_OR_M85
static void wait_for_feature_map(int8_t *out_feature)
{
    /*
     * Example using STM32 HSEM (hardware semaphore):
     *
     *   __WFI();                                   // sleep until M33 interrupt
     *   HAL_HSEM_FastTake(HSEM_ID_FEATURE_READY);  // claim the semaphore
     *   __DSB();                                   // flush cache before reading
     *   memcpy(out_feature, SHARED_SRAM_BASE, FEATURE_SAMPLES);
     *   HAL_HSEM_Release(HSEM_ID_FEATURE_READY, 0);
     *
     * For simulation (single-core M55 board) just fall through to the
     * normal DMA path in main().
     */
    (void)out_feature;
}
#endif

/* =========================================================================
 * main
 * ========================================================================= */
int main(void)
{
    HAL_Init();
    SystemClock_Config();   /* generated by CubeMX */
    peripheral_init();

    /* Initialise TFLite Micro — must succeed before entering the loop */
    int init_err = tflite_init();
    if (init_err != 0) {
        /* Signal error via LED or UART — replace with your board's mechanism */
        while (1) { __NOP(); }
    }

    /* Start first DMA transfer into buffer 0 */
    extern ADC_HandleTypeDef hadc1;   /* defined by CubeMX */
    HAL_ADC_Start_DMA(&hadc1, (uint32_t *)adc_buf[0], ADC_BUF_SAMPLES);

    while (1)
    {
#if RECHO_TARGET_M55_OR_M85
        /*
         * M55 / M85: on dual-core boards the M33 secondary core handles ADC
         * DMA and signals here when a feature map is ready.
         * On single-core M55 eval boards fall through to the DMA path below.
         */
        wait_for_feature_map(feature_map);   /* blocks until M33 signals */
#endif

        /* Wait for DMA to finish filling one full ADC window */
        if (!frame_ready) {
            __WFI();   /* sleep until next interrupt — saves power */
            continue;
        }
        frame_ready = 0;

        /* Process the buffer that is NOT currently being filled by DMA */
        uint8_t process_buf = adc_buf_active ^ 1;

        preprocess((const uint16_t *)adc_buf[process_buf], feature_map);

        result_class = run_inference(feature_map);

        /*
         * result_class is now the predicted class index (0 … n_classes-1).
         *
         * Options for acting on the result:
         *   - Write to a GPIO output (e.g. status LED per class)
         *   - Send over UART:  HAL_UART_Transmit(&huart2, &result_class, 1, 10);
         *   - Write to shared register for the host MCU to read
         *   - Trigger an alert if result_class == ANOMALY_CLASS
         */
    }
}
