/*
 * model_data.h
 *
 * Declaration for the TFLite Micro model byte array.
 * The definition lives in model_data.cc, generated by:
 *   python pipeline/convert.py
 *
 * Include this header in main.c. Link model_data.cc into your firmware project.
 */

#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char g_model_data[];
extern const unsigned int  g_model_data_len;

#ifdef __cplusplus
}
#endif

#endif /* MODEL_DATA_H */
