"""
Batch TFLite INT8 conversion for all trained Hopf oscillator models.

For each trained Keras checkpoint:
  1. Convert to TFLite INT8 with representative dataset calibration
  2. Validate accuracy drop < 2% post-quantisation
  3. Extract CMSIS-NN parameters (weights, biases, zero points, scales, shifts)
  4. Generate firmware/cmsis_nn_params_{model_name}.h
  5. Generate firmware/model_data_{model_name}.cc
  6. Print model size, peak activation RAM, and target chip compatibility

MULTI-INPUT MODEL HANDLING (Model E — late fusion):
  TFLite supports multiple inputs natively. Each input tensor gets its own
  quantisation parameters. The firmware header includes notes for dual DMA:
    buffer_x[200*100] — fed from x(t) ADC channel
    buffer_y[200*100] — fed from y(t) ADC channel
  On M85: both channels sampled simultaneously via dual DMA.

Model G (ridge regression) is sklearn-only — no TFLite conversion needed.

Usage:
    python -m pipeline.convert_all --checkpoint_dir checkpoints/
    python -m pipeline.convert_all --checkpoint_dir checkpoints/ --n_calib 200
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Optional

import numpy as np
from numpy.typing import NDArray

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# RAM budgets per MCU
MCU_RAM_LIMITS: dict[str, int] = {
    "M33": 64 * 1024,
    "M55": 128 * 1024,
    "M85": 256 * 1024,
}


def _rep_gen_single(feature_maps: NDArray, n_samples: int = 100):
    """Representative data generator for single-input models."""
    indices = np.random.default_rng(42).choice(
        len(feature_maps), size=min(n_samples, len(feature_maps)), replace=False,
    )
    for i in indices:
        sample = feature_maps[i].astype(np.float32)
        if sample.ndim == 2:
            sample = np.expand_dims(sample, axis=(0, -1))  # (1, 200, 100, 1)
        elif sample.ndim == 3:
            sample = np.expand_dims(sample, axis=0)        # (1, 200, 100, C)
        yield [sample]


def _rep_gen_fusion(x_maps: NDArray, y_maps: NDArray, n_samples: int = 100):
    """Representative data generator for Model E (dual-input)."""
    indices = np.random.default_rng(42).choice(
        len(x_maps), size=min(n_samples, len(x_maps)), replace=False,
    )
    for i in indices:
        x = np.expand_dims(np.expand_dims(x_maps[i].astype(np.float32), 0), -1)
        y = np.expand_dims(np.expand_dims(y_maps[i].astype(np.float32), 0), -1)
        yield [x, y]


def _compute_multiplier_shift(scale: float) -> tuple[int, int]:
    """Compute fixed-point multiplier and shift for CMSIS-NN."""
    if scale == 0:
        return 0, 0
    significand = scale
    shift = 0
    while significand < 0.5:
        significand *= 2.0
        shift -= 1
    while significand >= 1.0:
        significand /= 2.0
        shift += 1
    multiplier = int(round(significand * (1 << 31)))
    if multiplier == (1 << 31):
        multiplier //= 2
        shift += 1
    return multiplier, shift


def _generate_cmsis_header(
    layer_params: list[dict],
    output_path: Path,
    model_name: str,
    is_fusion: bool = False,
) -> None:
    """Generate firmware/cmsis_nn_params_{model_name}.h."""
    guard = f"CMSIS_NN_PARAMS_{model_name.upper()}_H"
    lines: list[str] = [
        f"/* Auto-generated CMSIS-NN parameters for {model_name} — do not edit */",
        f"/* Generated by recho_pipeline/pipeline/convert_all.py */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        '#include "arm_nnfunctions.h"',
        "",
    ]

    if is_fusion:
        lines += [
            "/* Model E — Late Fusion Dual-Input DMA Notes:",
            " * buffer_x[200*100] — fed from x(t) ADC DMA channel (channel 1)",
            " * buffer_y[200*100] — fed from y(t) ADC DMA channel (channel 2)",
            " *",
            " * On M85 with dual DMA (HAL_ADC_Start_DMA on ADC1 + ADC2):",
            " *   Both channels sampled simultaneously at 100 kHz.",
            " *   Double-buffered DMA: when buffer is full, CPU interrupt fires.",
            " *",
            " * On M33 (single ADC):",
            " *   Sample x(t) for 1s, then y(t) for 1s in alternating windows.",
            " *   Use time-multiplexed DMA with channel switch.",
            " */",
            "",
        ]

    for p in layer_params:
        safe_name = p["name"].replace("/", "_").replace(":", "_").replace(".", "_")

        if p.get("type") == "weight":
            flat = p["weight_data"].flatten()
            lines += [
                f"/* Layer weights: {p['name']} | shape: {p['shape']} */",
                f"static const int8_t {safe_name}[{len(flat)}] = {{",
            ]
            for start in range(0, len(flat), 16):
                row = flat[start:start + 16]
                lines.append("    " + ", ".join(str(int(v)) for v in row) + ",")
            lines.append("};")
            lines.append("")

            scales = p["scales"]
            n_ch = len(scales)
            multipliers = []
            shifts = []
            for s in scales:
                m, sh = _compute_multiplier_shift(s)
                multipliers.append(m)
                shifts.append(sh)

            lines.append(f"/* Per-channel quantisation — {safe_name} */")
            lines.append(f"static const int32_t {safe_name}_multiplier[{n_ch}] = {{")
            for start in range(0, n_ch, 8):
                lines.append("    " + ", ".join(str(v) for v in multipliers[start:start + 8]) + ",")
            lines.append("};")
            lines.append(f"static const int32_t {safe_name}_shift[{n_ch}] = {{")
            for start in range(0, n_ch, 8):
                lines.append("    " + ", ".join(str(v) for v in shifts[start:start + 8]) + ",")
            lines.append("};")
            lines.append("")

        elif p.get("type") == "bias":
            flat = p["bias_data"].flatten()
            lines += [
                f"/* Bias: {p['name']} — pre-scaled int32 for CMSIS-NN */",
                f"static const int32_t {safe_name}[{len(flat)}] = {{",
            ]
            for start in range(0, len(flat), 8):
                lines.append("    " + ", ".join(str(int(v)) for v in flat[start:start + 8]) + ",")
            lines.append("};")
            lines.append("")

        lines.append(f"#define {safe_name.upper()}_SCALE      {p['scales'][0]:.10f}f")
        lines.append(f"#define {safe_name.upper()}_ZERO_POINT  {p['zero_points'][0]}")
        lines.append("")

    lines += [
        "/*",
        " * Scratch buffer sizing:",
        " *   int32_t buf_size = arm_convolve_s8_get_buffer_size(",
        " *       &input_dims, &filter_dims);",
        " *   int8_t *scratch = (int8_t *)malloc(buf_size);",
        " */",
        "",
        f"#endif /* {guard} */",
        "",
    ]

    output_path.write_text("\n".join(lines))
    print(f"  [convert] Generated {output_path.name} ({len(lines)} lines)")


def _generate_model_cc(tflite_bytes: bytes, output_path: Path, model_name: str) -> None:
    """Generate firmware/model_data_{model_name}.cc as xxd-style C array."""
    lines = [
        f"/* Auto-generated TFLite Micro model data for {model_name} — do not edit */",
        f"/* Generated by recho_pipeline/pipeline/convert_all.py */",
        "",
        "#include <cstdint>",
        "",
        f"alignas(16) const unsigned char g_{model_name}_data[] = {{",
    ]
    for start in range(0, len(tflite_bytes), 12):
        row = tflite_bytes[start:start + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in row) + ",")
    lines += [
        "};",
        f"const unsigned int g_{model_name}_data_len = {len(tflite_bytes)};",
        "",
    ]
    output_path.write_text("\n".join(lines))
    print(f"  [convert] Generated {output_path.name} ({len(tflite_bytes):,} bytes)")


def _validate_accuracy(
    tflite_path: Path,
    test_features: NDArray,
    test_labels: NDArray,
    keras_acc: float,
    is_fusion: bool = False,
    y_features: Optional[NDArray] = None,
) -> float:
    """
    Run TFLite INT8 inference on test set and check accuracy drop < 2%.

    Returns:
        tflite_accuracy (float)
    """
    import tensorflow as tf

    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    correct = 0
    n_test = len(test_labels)

    for i in range(n_test):
        if is_fusion and y_features is not None:
            x_inp = test_features[i].astype(np.float32)
            y_inp = y_features[i].astype(np.float32)
            if x_inp.ndim == 2:
                x_inp = x_inp[np.newaxis, :, :, np.newaxis]
            if y_inp.ndim == 2:
                y_inp = y_inp[np.newaxis, :, :, np.newaxis]

            # Quantise inputs
            for k, inp_arr in enumerate([x_inp, y_inp]):
                if k < len(input_details):
                    scale = input_details[k]["quantization"][0]
                    zp = input_details[k]["quantization"][1]
                    q = (inp_arr / scale + zp).astype(np.int8)
                    interpreter.set_tensor(input_details[k]["index"], q)
        else:
            inp = test_features[i].astype(np.float32)
            if inp.ndim == 2:
                inp = inp[np.newaxis, :, :, np.newaxis]
            elif inp.ndim == 3:
                inp = inp[np.newaxis, ...]
            scale = input_details[0]["quantization"][0]
            zp = input_details[0]["quantization"][1]
            q = (inp / scale + zp).astype(np.int8)
            interpreter.set_tensor(input_details[0]["index"], q)

        interpreter.invoke()
        out = interpreter.get_tensor(output_details[0]["index"])
        pred = int(np.argmax(out))
        if pred == int(test_labels[i]):
            correct += 1

    tflite_acc = correct / n_test
    drop = keras_acc - tflite_acc
    status = "OK" if drop <= 0.02 else "WARNING — drop > 2%"
    print(f"  [validate] Keras acc={keras_acc:.4f}  TFLite INT8 acc={tflite_acc:.4f}  "
          f"drop={drop:.4f}  {status}")
    return tflite_acc


def _deployment_summary(
    tflite_path: Path,
    model_name: str,
) -> None:
    """Print model size, peak RAM, and MCU fit report."""
    import tensorflow as tf

    tflite_bytes = tflite_path.read_bytes()
    model_size = len(tflite_bytes)

    interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
    interpreter.allocate_tensors()
    tensor_details = interpreter.get_tensor_details()

    peak_ram = max(int(np.prod(d["shape"])) for d in tensor_details)

    print(f"\n  {'─'*50}")
    print(f"  {model_name}")
    print(f"  Model size:  {model_size:>10,} bytes  ({model_size / 1024:.1f} KB)")
    print(f"  Peak RAM:    {peak_ram:>10,} bytes  ({peak_ram / 1024:.1f} KB)")

    for mcu, limit in MCU_RAM_LIMITS.items():
        total = model_size + peak_ram
        fits = "YES" if total <= limit else "NO "
        print(f"  {mcu} ({limit // 1024:>3d} KB budget):  {fits}  "
              f"(total {total / 1024:.1f} KB)")

    # Check all tensors are int8/int32
    non_int = [d["name"] for d in tensor_details
               if d["dtype"] not in (np.int8, np.int32)]
    if non_int:
        print(f"  WARNING: {len(non_int)} non-INT tensors — partial CMSIS-NN coverage")
    else:
        print(f"  CMSIS-NN: ALL layers covered (production ready)")
    print(f"  {'─'*50}\n")


def convert_all(
    checkpoint_dir: str | Path = "checkpoints/",
    firmware_dir: str | Path = "firmware/",
    n_calib_samples: int = 100,
    n_clips_per_class: int = 20,
    n_classes: int = 5,
) -> None:
    """
    Convert all trained models to TFLite INT8 and generate firmware artefacts.
    """
    import tensorflow as tf

    ckpt = Path(checkpoint_dir)
    fw = Path(firmware_dir)
    fw.mkdir(parents=True, exist_ok=True)

    # Load calibration and test data
    print("\n[convert_all] Generating calibration data ...")
    from data.sample_data import generate_dataset_xy
    from pipeline.ingest import process_dataset
    from pipeline.features_xy import extract_y_features, extract_all_representations

    raw_x, raw_y, labels = generate_dataset_xy(
        n_clips_per_class=n_clips_per_class,
        n_classes=n_classes,
        cache=False,
    )
    x_proc = process_dataset(raw_x)
    y_proc = extract_y_features(raw_y)
    reps = extract_all_representations(x_proc, y_proc)
    print(f"  Calibration set: {len(labels)} clips")

    # -------------------------------------------------------------------------
    # Model registry — maps checkpoint name to input representation
    # -------------------------------------------------------------------------
    model_configs = [
        {
            "name": "model_a_cnn_x_only",
            "rep_key": "x_only",
            "expand_ch": True,
            "fusion": False,
        },
        {
            "name": "model_b_cnn_xy_dual",
            "rep_key": "xy_dual",
            "expand_ch": False,
            "fusion": False,
        },
        {
            "name": "model_c_cnn_phase",
            "rep_key": "phase",
            "expand_ch": True,
            "fusion": False,
        },
        {
            "name": "model_d_cnn_angle",
            "rep_key": "angle",
            "expand_ch": True,
            "fusion": False,
        },
        {
            "name": "model_e_cnn_xy_fusion",
            "rep_key": "x_only",          # primary (x input)
            "expand_ch": True,
            "fusion": True,
        },
        {
            "name": "model_f_depthwise_cnn",
            "rep_key": "xy_dual",
            "expand_ch": False,
            "fusion": False,
        },
    ]

    print(f"\n[convert_all] Converting {len(model_configs)} models ...")

    for cfg in model_configs:
        name = cfg["name"]
        ckpt_path = ckpt / f"{name}_best.keras"

        print(f"\n{'='*60}")
        print(f"[convert_all] {name}")
        print(f"{'='*60}")

        if not ckpt_path.exists():
            print(f"  SKIP — checkpoint not found: {ckpt_path}")
            continue

        # Load model
        try:
            model = tf.keras.models.load_model(str(ckpt_path))
            print(f"  Loaded checkpoint: {ckpt_path.name}")
        except Exception as e:
            print(f"  ERROR loading model: {e}")
            continue

        # Representative data generator
        calib_features = reps[cfg["rep_key"]]
        if cfg["fusion"]:
            def make_rep_gen(x_m=reps["x_only"], y_m=reps["y_only"],
                             n=n_calib_samples):
                def gen():
                    yield from _rep_gen_fusion(x_m, y_m, n)
                return gen
            rep_gen = make_rep_gen()
        else:
            def make_rep_gen(feat=calib_features, expand=cfg["expand_ch"],
                             n=n_calib_samples):
                def gen():
                    for sample in _rep_gen_single(feat, n):
                        if expand and sample[0].ndim == 3:
                            sample = [np.expand_dims(sample[0], -1)]
                        yield sample
                return gen
            rep_gen = make_rep_gen()

        # TFLite INT8 conversion
        tflite_path = fw / f"{name}.tflite"
        try:
            converter = tf.lite.TFLiteConverter.from_keras_model(model)
            converter.optimizations = [tf.lite.Optimize.DEFAULT]
            converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
            converter.inference_input_type = tf.int8
            converter.inference_output_type = tf.int8
            converter.representative_dataset = rep_gen
            tflite_model = converter.convert()
            tflite_path.write_bytes(tflite_model)
            print(f"  TFLite saved: {tflite_path.name} ({len(tflite_model):,} bytes)")
        except Exception as e:
            print(f"  ERROR during TFLite conversion: {e}")
            continue

        # Accuracy validation
        try:
            keras_preds = model.predict(
                [np.expand_dims(reps["x_only"].astype(np.float32), -1),
                 np.expand_dims(reps["y_only"].astype(np.float32), -1)]
                if cfg["fusion"] else
                (np.expand_dims(calib_features.astype(np.float32), -1)
                 if cfg["expand_ch"]
                 else calib_features.astype(np.float32)),
                verbose=0,
            )
            keras_acc = float(np.mean(np.argmax(keras_preds, 1) == labels))
            _validate_accuracy(
                tflite_path, calib_features, labels,
                keras_acc, is_fusion=cfg["fusion"],
                y_features=reps["y_only"] if cfg["fusion"] else None,
            )
        except Exception as e:
            print(f"  WARNING: accuracy validation failed: {e}")

        # Extract CMSIS-NN parameters
        try:
            interpreter = tf.lite.Interpreter(model_path=str(tflite_path))
            interpreter.allocate_tensors()
            tensor_details = interpreter.get_tensor_details()
            layer_params: list[dict] = []
            for detail in tensor_details:
                quant = detail.get("quantization_parameters", {})
                scales = quant.get("scales", np.array([]))
                zero_points = quant.get("zero_points", np.array([]))
                if len(scales) == 0:
                    continue
                tensor_data = interpreter.get_tensor(detail["index"])
                param: dict = {
                    "name": detail["name"],
                    "shape": list(detail["shape"]),
                    "dtype": str(detail["dtype"]),
                    "scales": scales.tolist(),
                    "zero_points": zero_points.tolist(),
                }
                if detail["dtype"] == np.int8 and len(detail["shape"]) >= 2:
                    param["type"] = "weight"
                    param["weight_data"] = tensor_data
                elif detail["dtype"] == np.int32:
                    param["type"] = "bias"
                    param["bias_data"] = tensor_data
                layer_params.append(param)

            # Generate C header
            header_path = fw / f"cmsis_nn_params_{name}.h"
            _generate_cmsis_header(layer_params, header_path, name,
                                   is_fusion=cfg["fusion"])

            # Generate model_data.cc
            cc_path = fw / f"model_data_{name}.cc"
            _generate_model_cc(tflite_path.read_bytes(), cc_path, name)

        except Exception as e:
            print(f"  WARNING: code generation failed: {e}")

        # Deployment summary
        try:
            _deployment_summary(tflite_path, name)
        except Exception as e:
            print(f"  WARNING: deployment summary failed: {e}")

    print(f"\n[convert_all] All artefacts saved to {fw.resolve()}")
    print("  Files generated:")
    for f in sorted(fw.iterdir()):
        print(f"    {f.name}  ({f.stat().st_size / 1024:.1f} KB)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Batch TFLite INT8 conversion")
    parser.add_argument("--checkpoint_dir", type=str, default="checkpoints/")
    parser.add_argument("--firmware_dir", type=str, default=None)
    parser.add_argument("--n_calib", type=int, default=100)
    parser.add_argument("--n_clips", type=int, default=20)
    parser.add_argument("--n_classes", type=int, default=5)
    args = parser.parse_args()

    fw_dir = args.firmware_dir or str(ROOT / "firmware")

    convert_all(
        checkpoint_dir=ROOT / args.checkpoint_dir,
        firmware_dir=fw_dir,
        n_calib_samples=args.n_calib,
        n_clips_per_class=args.n_clips,
        n_classes=args.n_classes,
    )


if __name__ == "__main__":
    main()
